// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmqCaJ2Q7QfqSwUBmTs4BOFG2KnkG0dc',
    appId: '1:882542361908:android:1788fab85570b6b3193961',
    messagingSenderId: '882542361908',
    projectId: 'classroom-automation-2c6e8',
    databaseURL: 'https://classroom-automation-2c6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classroom-automation-2c6e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AJPfz3jgwtHASAOdv19SKJmNYkXAQnI',
    appId: '1:882542361908:ios:9f3837c325ef335d193961',
    messagingSenderId: '882542361908',
    projectId: 'classroom-automation-2c6e8',
    databaseURL: 'https://classroom-automation-2c6e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classroom-automation-2c6e8.appspot.com',
    iosBundleId: 'com.example.aplikasiKontrolKelas',
  );
}
